language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true

env:
  global:
    - PHALCON_VERSION="v3.4.0"

before_install:
  - ulimit -c unlimited -S || true
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com $GH_TOKEN; fi;
  - export PHP_MAJOR="$(echo $TRAVIS_PHP_VERSION | cut -d '.' -f 1)"

install:
  - bash $TRAVIS_BUILD_DIR/spec/install_phalcon.sh
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest --optimize-autoloader
  - phpenv rehash
  - ls -al `$(phpenv which php-config) --extension-dir`
  - $(phpenv which php) -v
  - $(phpenv which php) -m

script: vendor/bin/kahlan

after_success:
  - "if [ $(phpenv version-name) = '7.2' ]; then curl -F 'json_file=@coveralls.json' https://coveralls.io/api/v1/jobs --verbose; fi"
